Resolve spec inside  and json_array and json_object
ebi-ait/json-converter pull request #4
Opened 2021-02-05 19:19 UTC by aaclan-ebi

2021-02-06 12:58 UTC, ke4 requested changes
Excellent work! 👍 💯 
2 tiny modification request:
- Please change the error message according to the condition change
- bump the version in setup.py to be able to deploy pipy with a new version. I would bump it to 0.4.0.
Many thanks

2021-02-06 12:58 UTC, ke4 commented on json_converter/json_mapper.py
>              raise UnreadableSpecification('Expecting exactly 1 JSON literal value.')
I think the message should be: `Expecting 2 or 3 JSON literal value.`

2021-02-08 15:37 UTC, aaclan-ebi commented
@ke4 I'm still not sure if there's a better way to provide the use case you needed. I'll let you merge and release this to PyPI.

2021-02-10 10:44 UTC, MightyAx commented
I was worried that this change would break my existing uses of the $object literal to use literal json that I did not want to be converted but having tested the changes, that is not the case 👍

@aaclan-ebi, @ke4: The change definitely allows you to build structure (the key/value attributes) around mapped attributes.
Can this code also be used for unmapped attributes? This would simplify some code where I currently must do this manually.

```python
spec = {
  'A': ['a'],
  'others': ['$unmapped', map_to, {
    'KEY': ['$key'],
    'VALUE': '$value'
  }]
}

input_object = {
  'a': 1
  'b': 2
  'c': 3
}

result = {
  'A': 1
  'others': [
    {
      'KEY': 'b',
      'VALUE': 2
    },
    {
      'KEY': 'c',
      'VALUE': 3
    }
  ]
}
```

Currently to achieve the above I would keep a list of the mapped keys next to spec, pop them from the dictionary and map the 'others' object separately. Is that still the best way to dos this?

```python
remove_keys = ['a']

others = copy(input_object)
for key in remove_keys:
  others.pop(key)
```
so now I have this others object:
```
others = {
  'b': 2
  'c': 3
}
```
what is the syntax to make this:
```
[
  {
    'KEY': 'b',
    'VALUE': 2
  },
  {
    'KEY': 'c',
    'VALUE': 3
  }
]
```
or perhaps this, whichever is easier:
```
{
  'others': [
    {
      'KEY': 'b',
      'VALUE': 2
    },
    {
      'KEY': 'c',
      'VALUE': 3
    }
  ]
}
```

2021-02-12 11:32 UTC, ke4 approved these changes

2021-02-12 11:32 UTC, ke4 commented on README.md
> +            'metadata': ['$array', values, True]
Please, replace the metadata key with attributes, as that is the key in the resulting JSON.
```suggestion
            'attributes': ['$array', values, True]
```

2021-02-12 12:16 UTC, merged